### ISSUE TITLE
Documents that does not exist causes issues

### ISSUE THREAD

**Issue by andybdahl** [brotoo25/firestore-coroutines#3]
Using DocumentReference.await(parser:): T causes problems on documents that does not exist. I expect the coroutine to resume with an exception, but it resumes and force unwraps the result in the parser, even when the result is a document that does not exist (e.g an empty reference). Please fix this issue, as is makes the await(parser:) function not able to be used for checking whether or not a document needs to be created at the specified location.

# Suggested fix
´´´
suspend fun <T : Any> DocumentReference.await(parser: (documentSnapshot: DocumentSnapshot) -> T): T {
        return suspendCoroutine { continuation ->
            get().addOnCompleteListener {

                if (it.isSuccessful && it.result != null && it.result!!.exists()) {
                    continuation.resume(parser.invoke(it.result!!))
                } else if (it.isSuccessful && it.result != null && !it.result!!.exists()) {
                    continuation.resumeWithException(DocumentDoesNotExistsException())
                } else if (it.exception != null){
                    continuation.resumeWithException(it.exception!!)
                } else {
                    continuation.resumeWithException(EmptyStackException())
                }
            }
        }
    }
´´´

**Comment by brotoo25** [comment]
New version (0.0.7) includes a fix for this issue.
